name: ocaml-ci

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: tests

    steps:
      - uses: actions/checkout@v4

      - run: |
          sudo apt update
          sudo apt install -y ocaml opam qemu-user binutils-riscv64-unknown-elf
          opam init --disable-sandboxing -y
          eval $(opam env)
          opam install dune alcotest ppx_expect ppx_deriving --yes
          dune build
          export REPO_ROOT="$PWD"
          export EMULATOR="qemu-riscv64"
          dune test
