name: ocaml-ci

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: tests

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-version: "5.2.1"
          opam-repository: "https://github.com/ocaml/opam-repository "
          packages: "dune,alcotest"

      - name: build-and-test
        run: |
            dune build
            dune test
