name: ocaml-ci

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: tests

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup
        run: |
          sudo apt update
          sudo apt install -y ocaml opam
          opam init --disable-sandboxing -y
          eval $(opam env)
          opam install . --deps-only --with-test --yes

      - name: test
        run: |
          for dir in */; do
            if [ -f "${dir}dune-project" ]; then  
              cd "$dir"
              dune build
              dune test
              exit_code=$?
              if [$exit_code -neq 0]; then
                exit $exit_code
              fi
              cd ..
            fi
          done
