name: ocaml-ci

on:
  push:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: tests

    steps:
      - uses: actions/checkout@v4

      - run: |
          sudo apt update
          sudo apt install -y ocaml opam
          opam init --disable-sandboxing -y
          eval $(opam env)
          opam install dune --yes
          opam install alcotest --yes
          opam install . --deps-only --yes
    
      - run: |
          for dir in */; do
            if [ -f "${dir%?}/dune-project" ]; then  
              cd "$dir"
              dune build
              dune runtest
              exit_code=$?
              if [$exit_code -neq 0]; then
                exit $exit_code
              fi
              cd ..
            fi
          done
