name: ocaml-ci

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: tests

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set-up
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "5.2"

      - run: opam install . --deps-only --with-test

      - run: |
          for dir in */; do
            if [ -f "$dir/dune-project" ]; then
              cd "$dir"
              dune build
              dune runtest
              cd ..
            fi
          done
